version: '2'

services:
  rabbitmq:
    image: bitnami/rabbitmq
    environment:
      - RABBITMQ_USERNAME=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
